In [ ]:
"""
Option 1
https://stackoverflow.com/questions/49710537/pytorch-gensim-how-to-load-pre-trained-word-embeddings

Option 2
https://discuss.pytorch.org/t/can-we-use-pre-trained-word-embeddings-for-weight-initialization-in-nn-embedding/1222/5

"""

In [2]:
import torch
import torch.nn as nn


Create a float tensor contraining the "pretrained" weights

In [3]:
vocab_size = 3
e_dimensions = 5
weights = torch.randn((vocab_size, e_dimensions), dtype=float)
print(weights)

tensor([[-0.8101, -0.2536,  0.3791, -1.1892, -0.5960],
        [ 0.4989,  0.5630, -0.2330, -1.9416,  0.9052],
        [ 0.6020, -3.3878, -1.4428,  0.1812,  0.1920]], dtype=torch.float64)


## Option 1

Create the embedding layer and assign the "pretrained" weights

In [4]:
embedding = nn.Embedding.from_pretrained(weights)

Get the embeddings

In [5]:
# For the index 1
input = torch.LongTensor([1])
print(embedding(input))

tensor([[ 0.4989,  0.5630, -0.2330, -1.9416,  0.9052]], dtype=torch.float64)


## Option 2

Create the embedding layer, then copy the "pretrained" weights

In [8]:
embedding = nn.Embedding(vocab_size, e_dimensions)
#pretrained_weight is be a numpy matrix of shape (vocab_size, e_dimensions)
embedding.weight.data.copy_(weights)
# If we want to freeze it
embedding.weight.requires_grad = False
# There could be an error with the optimizer. check the solution (use filter)

Get the embedding

In [9]:
# For the index 1
input = torch.LongTensor([1])
print(embedding(input))

tensor([[ 0.4989,  0.5630, -0.2330, -1.9416,  0.9052]])


## These methods work, however there could be words in out vocabulary that the pretrained embeddings do not have.

## Then, for each of those words assign a random embedding.