In [ ]:
"""
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
"""

In [1]:
import torch

Construct a 5x3 matrix, uninintialized

In [13]:
x = torch.empty(5,3)
print(x)

tensor([[ 4.1882e-37,  0.0000e+00,  4.6816e-01],
        [ 6.8335e-01,  1.9801e+00, -5.3833e-01],
        [ 7.4235e-01,  1.3128e+00,  1.9832e+00],
        [-1.7516e+00, -7.2975e-01, -4.2010e+00],
        [ 7.8774e-01, -6.1153e-01, -4.7744e-01]])


Construct a randomly initialized matrix

In [12]:
x = torch.randn(5,3)
print(x)

tensor([[ 0.6804,  0.0577,  0.4682],
        [ 0.6833,  1.9801, -0.5383],
        [ 0.7423,  1.3128,  1.9832],
        [-1.7516, -0.7298, -4.2010],
        [ 0.7877, -0.6115, -0.4774]])


Construct a matrix filled zeros and of dtype long

In [14]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [17]:
x = torch.tensor([5.5, 3])
print(x)
print(x.shape)
print(x.dim())

tensor([5.5000, 3.0000])
torch.Size([2])
1


Create a tensor based on an existing tensor. The new tensor will reuse properties of the input tensor

In [19]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

y = torch.rand_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.8147, 0.3207, 0.9838],
        [0.8044, 0.0951, 0.8529],
        [0.0630, 0.0926, 0.1172],
        [0.5287, 0.3986, 0.8493],
        [0.6597, 0.5571, 0.4114]])


Get its size

In [21]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### Operations

In [26]:
print(x)
print(y)
print(x+y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.8147, 0.3207, 0.9838],
        [0.8044, 0.0951, 0.8529],
        [0.0630, 0.0926, 0.1172],
        [0.5287, 0.3986, 0.8493],
        [0.6597, 0.5571, 0.4114]])
tensor([[1.8147, 1.3207, 1.9838],
        [1.8044, 1.0951, 1.8529],
        [1.0630, 1.0926, 1.1172],
        [1.5287, 1.3986, 1.8493],
        [1.6597, 1.5571, 1.4114]], dtype=torch.float64)


In [27]:
print(torch.add(x,y))

tensor([[1.8147, 1.3207, 1.9838],
        [1.8044, 1.0951, 1.8529],
        [1.0630, 1.0926, 1.1172],
        [1.5287, 1.3986, 1.8493],
        [1.6597, 1.5571, 1.4114]], dtype=torch.float64)


In [28]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[1.8147, 1.3207, 1.9838],
        [1.8044, 1.0951, 1.8529],
        [1.0630, 1.0926, 1.1172],
        [1.5287, 1.3986, 1.8493],
        [1.6597, 1.5571, 1.4114]])


In [31]:
z = y.add(x)
print(z)

tensor([[1.8147, 1.3207, 1.9838],
        [1.8044, 1.0951, 1.8529],
        [1.0630, 1.0926, 1.1172],
        [1.5287, 1.3986, 1.8493],
        [1.6597, 1.5571, 1.4114]], dtype=torch.float64)
tensor([[0.8147, 0.3207, 0.9838],
        [0.8044, 0.0951, 0.8529],
        [0.0630, 0.0926, 0.1172],
        [0.5287, 0.3986, 0.8493],
        [0.6597, 0.5571, 0.4114]])


In [33]:
print(y)
print(y[:,1])

tensor([[0.8147, 0.3207, 0.9838],
        [0.8044, 0.0951, 0.8529],
        [0.0630, 0.0926, 0.1172],
        [0.5287, 0.3986, 0.8493],
        [0.6597, 0.5571, 0.4114]])
tensor([0.3207, 0.0951, 0.0926, 0.3986, 0.5571])


To resize/reshape a tensor use torch.view

In [39]:
x = torch.rand(4,4)
print(x)
print(x.size())

y = x.view(16)
print(y)
print(y.size())

z = x.view(-1, 8)   # the size -1 is inferred from other dimensions
print(z)
print(z.size())

tensor([[0.8856, 0.0319, 0.4412, 0.3004],
        [0.9466, 0.3926, 0.3124, 0.7216],
        [0.0106, 0.3201, 0.2930, 0.9346],
        [0.3700, 0.8195, 0.9686, 0.2707]])
torch.Size([4, 4])
tensor([0.8856, 0.0319, 0.4412, 0.3004, 0.9466, 0.3926, 0.3124, 0.7216, 0.0106,
        0.3201, 0.2930, 0.9346, 0.3700, 0.8195, 0.9686, 0.2707])
torch.Size([16])
tensor([[0.8856, 0.0319, 0.4412, 0.3004, 0.9466, 0.3926, 0.3124, 0.7216],
        [0.0106, 0.3201, 0.2930, 0.9346, 0.3700, 0.8195, 0.9686, 0.2707]])
torch.Size([2, 8])


If there is only one element tensor, use .item() to get the value as a Python number

In [40]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.7757])
0.7756971120834351


### NumPy Bridge

Convert Torch Tensor to a NumPy Array

In [42]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


See how the numpy array changed in value

In [44]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting Numpy Array to Torch Tensor

In [46]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using .to method

In [48]:
# this cell runs only if CUDA is available
# we will use ``torch device`` object to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
else:
    print("GPU no available")

GPU no available
