In [ ]:
"""
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html
"""

In [1]:
import torch

Create a tensor and set "requires_grad=True" to track computation with it

In [22]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation

In [23]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y was created as a result of an operation, so it has a "grad_fn"

In [24]:
print(y.grad_fn)

Do more operations on y

In [25]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


".requires_grad_(...)" changes an existing Tensor's "requires_grad" flag in_place.

In [26]:
a = torch.randn(2,2)
a = ( (a * 3) / (a - 1) )
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


### Gradients

In [27]:
out.backward()

print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You can stop autograd from tracking history on Tensors

In [28]:
x = torch.randn(3, requires_grad=True)
print(x.requires_grad)
print( (x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


or by using "detach"

In [37]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())
print(x)
print(y)
print(x+1)
print(y)

True
False
tensor(True)
tensor([ 1.3338,  0.3566, -0.0349], requires_grad=True)
tensor([ 1.3338,  0.3566, -0.0349])
tensor([2.3338, 1.3566, 0.9651], grad_fn=<AddBackward0>)
tensor([ 1.3338,  0.3566, -0.0349])
