In [15]:

import torch
import torch.nn as nn
import numpy as np
import torch.optim as optim


In [16]:
n_users = 2 # los user_ids comienzan desde 1, asi que hay que agregar 1 row mas, 0 no cuenta
n_items = 10
embed_size = 5
bias = 1

In [17]:
user_embeddings= nn.Embedding(n_users+1, embed_size)
item_embeddings = nn.Embedding(n_items+1, embed_size)
bias_users = nn.Embedding(n_users+1, bias)
bias_items = nn.Embedding(n_items+1, bias)

In [18]:
print(user_embeddings)
print(item_embeddings)
print(bias_users)
print(bias_items)


Embedding(3, 5)
Embedding(11, 5)
Embedding(3, 1)
Embedding(11, 1)


### Ver algunos embeddings

In [19]:
userid = 1
itemid = 3
rating = 4.5

y_range = (0, 5.5)

print("User {} embeddings".format(userid))
userid = torch.LongTensor([userid])
print(user_embeddings(userid))

print("Item {} embeddings".format(itemid))
itemid = torch.LongTensor([itemid])
print(item_embeddings(userid))

print("User bias {} embeddings".format(userid))
userid = torch.LongTensor([userid])
print(bias_users(userid))

print("Item bias {} embeddings".format(itemid))
itemid = torch.LongTensor([itemid])
print(bias_items(userid))


User 1 embeddings
tensor([[ 0.4479, -1.0190, -0.0465,  0.1341, -0.2730]],
       grad_fn=<EmbeddingBackward>)
Item 3 embeddings
tensor([[ 1.2285, -0.8647,  0.1552,  1.3463,  1.1785]],
       grad_fn=<EmbeddingBackward>)
User bias tensor([1]) embeddings
tensor([[0.3460]], grad_fn=<EmbeddingBackward>)
Item bias tensor([3]) embeddings
tensor([[-0.3841]], grad_fn=<EmbeddingBackward>)


In [20]:
print(user_embeddings(userid).shape)
print(item_embeddings(itemid).shape)

dot = user_embeddings(userid).squeeze().dot(item_embeddings(itemid).squeeze())
print(dot)
res = dot + bias_users(userid).squeeze() + bias_items(itemid).squeeze()
print(res)

torch.Size([1, 5])
torch.Size([1, 5])
tensor(1.7964, grad_fn=<DotBackward>)
tensor(3.4217, grad_fn=<AddBackward0>)


In [26]:
pred = torch.sigmoid(res) * (y_range[1]-y_range[0] + y_range[0])
print(pred)

tensor(5.3261, grad_fn=<MulBackward0>)


In [22]:
criterion = nn.MSELoss()

rating = torch.FloatTensor([rating])
loss = criterion(pred, rating)
print(loss)

loss.backward()

tensor(0.6824, grad_fn=<MseLossBackward>)


In [23]:
"""
print(bias_items.weight)
print(bias_items.weight.grad)

learning_rate = 0.01
z = learning_rate * bias_items.weight.grad
print(z)
f = bias_items.weight - z
print(f)
"""

'\nprint(bias_items.weight)\nprint(bias_items.weight.grad)\n\nlearning_rate = 0.01\nz = learning_rate * bias_items.weight.grad\nprint(z)\nf = bias_items.weight - z\nprint(f)\n'

In [24]:
learning_rate = 0.01
with torch.no_grad():
    user_embeddings.weight -= learning_rate * user_embeddings.weight.grad
    item_embeddings.weight -= learning_rate * item_embeddings.weight.grad
    bias_users.weight -= learning_rate * bias_users.weight.grad
    bias_items.weight -= learning_rate * bias_items.weight.grad

In [25]:
print("User {} embeddings".format(userid))
userid = torch.LongTensor([userid])
print(user_embeddings(userid))

print("Item {} embeddings".format(itemid))
itemid = torch.LongTensor([itemid])
print(item_embeddings(userid))

print("User bias {} embeddings".format(userid))
userid = torch.LongTensor([userid])
print(bias_users(userid))

print("Item bias {} embeddings".format(itemid))
itemid = torch.LongTensor([itemid])
print(bias_items(userid))

User tensor([1]) embeddings
tensor([[ 0.4490, -1.0142, -0.0477,  0.1280, -0.2736]],
       grad_fn=<EmbeddingBackward>)
Item tensor([3]) embeddings
tensor([[ 1.2285, -0.8647,  0.1552,  1.3463,  1.1785]],
       grad_fn=<EmbeddingBackward>)
User bias tensor([1]) embeddings
tensor([[0.3432]], grad_fn=<EmbeddingBackward>)
Item bias tensor([3]) embeddings
tensor([[-0.3841]], grad_fn=<EmbeddingBackward>)
